### PR TITLE
Bundled Dependent bot PRs - SidekiqCron, Rails HTML sanitizer * 2, rubocop Rails* 2, Omnibus Software

### PR DESCRIPTION
**Pull request by ayush-billore**
### Issues Resolved

https://github.com/chef/supermarket/pull/2812
https://github.com/chef/supermarket/pull/2818
https://github.com/chef/supermarket/pull/2819
https://github.com/chef/supermarket/pull/2821
https://github.com/chef/supermarket/pull/2822
https://github.com/chef/supermarket/pull/2823

### Check List

- [ ] New functionality includes tests
- [ ] All buildkite tests pass
- [ ] Full omnibus build and tests in buildkite pass
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Comment by ayush-billore** [comment]
Adhoc build link - https://buildkite.com/chef/chef-supermarket-main-omnibus-adhoc/builds/552

**Review by dheerajd-msys — APPROVED** [review]

**Comment by dheerajd-msys** [comment]
@saghoshprogress Please merge this.

**Comment by RajeshPaul38** [comment]
@ayush-billore @dheerajd-msys the build is red. @saghoshprogress pls don't merge it.

**Comment by ayush-billore** [comment]
@RajeshPaul38 Sorry I missed to attach the Adhoc build with IGNORE_CACHE=true. It is Green.

Build Link - https://buildkite.com/chef/chef-supermarket-main-omnibus-adhoc/builds/553

**Review by RajeshPaul38 — APPROVED** [review]
@saghoshprogress pls merge it.

**Pull request merged**
