### PR TITLE
Explicitly define expeditor promote config

### PR DESCRIPTION
**Pull request by jeremiahsnapp**
Signed-off-by: Jeremiah Snapp <jeremiah@chef.io>

### CODE REVIEW

**Comment by robbkidd** [comment]
Does this cause new behavior? If so, what is new?

Does being explicit here solve a problem? If so, what's the problem?

**Comment by jeremiahsnapp** [comment]
No new behavior. We're just explicitly defining these expeditor default values to be consistent across our server projects.

**Comment by robbkidd** [comment]
Ah! So, this is an explicit ordering of the channels through which this project's artifacts get promoted instead of relying on [the default for projects that define a `product_key`](https://expeditor.chef.io/docs/reference/promote/#promotion-channels)?

**Comment by jeremiahsnapp** [comment]
Yes, that's correct @robbkidd. These channels are already ordered this way by default. Now they are explicitly defined in the expeditor config.

**Comment by robbkidd** [comment]
Bueno! Thanks for the explanation!

**Pull request merged**
