### PR TITLE
add type and order parameters to the tools API search endpoint

### LINKED ISSUE #1454: API to support tools search by type
Tools uploaded to the supermarket have a `Type` field (Handler, Compliance Profile, etc).

This feature request is for adding a `type` parameter to the search API.

It will allow tools like inspec to only list compliance profiles via:

```
inspec supermarket profiles
```

### PR DESCRIPTION
**Pull request by robbkidd**
Updated the tools-search API endpoint to behave more like the UI search logic. 

* Adds a type parameter so that tool results can be filtered by tool type.
* Adds order parameter to specify ordering of results.

Fixes #1454

### CODE REVIEW

**Comment by robbkidd** [comment]
@thommay Surgical add-on to the tools-search as discussed. Available to review?

/cc @nathenharvey

**Comment by robbkidd** [comment]
@alexpop Here's the next incremental improvement to Supermarket's tool-search API to filter results by tool type.

**Comment by alexpop** [comment]
Looks great, thanks for working on this Robb

**Comment by robbkidd** [comment]
Thanks, folks! Sent this change into the pipeline.

**Pull request merged**
