### PR TITLE
fix schema metadata create/update

### PR DESCRIPTION
**Pull request by rmoriz**
`dateModified` and `datePublished` are the wrong way around here, causing wrong dates on google search results (since ~2014 I guess).

 For example:

ohai cookbook - chef supermarket

ohai cookbook - google-suche-1

### CODE REVIEW

**Comment by rmoriz** [comment]
travis failure caused by `bundle exec bundle-audit check --update` on one ruby platform => unrelated. See #1754 #1755 for workaround

**Comment by rmoriz** [comment]
github sadly closed the PR… can you cherry-pick the comit?

**Comment by rmoriz** [comment]
ping @robbkidd

**Comment by robbkidd** [comment]
Hi, @rmoriz! This PR started me thinking that reusing the endpoint that searches for cookbooks didn't fit well with a new releases feed. I started in on some work for a feed like that on #1740. I'd love some feedback on the proposal there.

**Comment by rmoriz** [comment]
just cherry-pick the change. You're hurting supermarkt's google ranking right now so much.

**Comment by rmoriz** [comment]
chef cookbook openssl - google-suche

google is ranking everything on supermarket as 8+ year old stuff and this is only caused by the bug that is resolved in 0a91597

**Comment by robbkidd** [comment]
Ooooooh. I see. You're right, I had conflated the two. This has nothing to do with the RSS feed.

On it. Thanks, @rmoriz.

**Pull request closed without merging**
