### PR TITLE
adds a link to Chef status page to footer

### PR DESCRIPTION
**Pull request by nellshamrell**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
:+1:

**Comment by lamont-granquist** [comment]
although...  specs?

**Comment by nellshamrell** [comment]
Good point.  Will add those in and merge.

**Comment by kowal** [comment]
+1 for that.

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @nellshamrell

[Please sign the CLA here.](https://supermarket-staging.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @nellshamrell

[Please sign the CLA here.](https://supermarket-staging.chef.io/become-a-contributor)

**Comment by nellshamrell** [comment]
Spec added!

**Comment by lamont-granquist** [comment]
:+1:

**Pull request merged**
