### PR TITLE
Accept either SPDX standard licenses or DK generated licenses

### PR DESCRIPTION
**Pull request by tas50**
Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by robbkidd** [comment]
@tas50 I agree, though, can you cite the source for this being the standard?

**Comment by tas50** [comment]
Updated to accept either SPDX or DK licenses, but not the non-standard strings we didn't use anywhere

**Comment by robbkidd** [comment]
:+1: I'll clean up the tests.

**Comment by robbkidd** [comment]
[QM003](https://github.com/chef-cookbooks/cookbook-quality-metrics/blob/35bddc5af54eb8478b2307f7b6d231f03cf61ae9/quality-metrics/qm-003-license.md) updated to specify SPDX format for licenses.

**Pull request merged**
