### PR TITLE
omit the foodcritic working directory from metric feedback

### LINKED ISSUE #1348: Make foodcritic output less verbose
It would be nice if the Foodcritic criticism output was a little neater on the page. It would be great to trim the temporary work directory from the start of the path given in the output, reducing the noise in the feedback. For example, this: 
`FC005: Avoid repetition of resource declarations: /tmp/cook/dbb1ab441e2236a1faffddb7/docker/libraries/docker_service_manager_sysvinit_debian.rb:5
`
would be cleaner as this: 
`FC005: Avoid repetition of resource declarations: docker/libraries/docker_service_manager_sysvinit_debian.rb:5`

### PR DESCRIPTION
**Pull request by robbkidd**
Fixes #1348

Based on the work of Logan McDonald in #1349

TODO Reach Goals:
- [x] change all assertions over to rspec-style expectations
- [ ] speed up the tests somehow, maybe by not running foodcritic because we're not testing foodcritic itself

### CODE REVIEW

**Comment by nellshamrell** [comment]
👍 

I would hold off on speeding up the tests until the debate over whether to retire Foodcritic is decided.

**Comment by tas50** [comment]
^ that

**Comment by nellshamrell** [comment]
👍

**Comment by nellshamrell** [comment]
I stand by my 👍

**Comment by robbkidd** [comment]
Excellent.

**Pull request merged**
