### PR TITLE
add almalinux and rocky linux logos

### PR DESCRIPTION
**Pull request by Stromweld**
### Description

Adding almalinux and rockylinux logos

### Check List

- [ ] New functionality includes tests
- [ ] All buildkite tests pass
- [ ] Full omnibus build and tests in buildkite pass
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Comment by Stromweld** [comment]
failing tests aren't related to the changes in this PR

**Comment by dheerajd-msys** [comment]
I've verified this PR on **_Rocky linux 8_** & **_AlmaLinux 8_** both and working fine.

Attaching screenshots : 
1. AlmaLinux
Screenshot 2023-03-15 at 3 32 04 PM
2. Rocky Linux
Screenshot 2023-03-15 at 3 32 13 PM

**Comment by dheerajd-msys** [comment]
Thanks @Stromweld for raising the PR. All your changes are committed here https://github.com/chef/supermarket/pull/3071

**Comment by saghoshprogress** [comment]
has been taken care in a different PR

**Pull request closed without merging**
