### PR TITLE
Build Supermarket on SLES

### PR DESCRIPTION
**Pull request by dheerajd-msys**
Signed-off-by: saghoshprogress <saghosh@progress.com>

### Description

Build Supermarket on SLES

### Issues Resolved

Fixes https://github.com/chef/supermarket/issues/1957

Buildkite Build: https://buildkite.com/chef/chef-supermarket-main-omnibus-adhoc/builds/181

### Check List

- [ ] New functionality includes tests
- [x] All buildkite tests pass
- [x] Full omnibus build and tests in buildkite pass
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [x] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Comment by tas50** [comment]
We'll want to rebase this once we get the rails upgrade / nodejs fixes merged and then we can kick off an adhoc.

**Comment by tas50** [comment]
https://buildkite.com/chef/chef-supermarket-master-omnibus-adhoc/builds/137#5f819aa3-dfa6-41d8-a01f-0d6c38561751

**Review by tas50 — CHANGES_REQUESTED** [review]
This is failing in buildkite adhoc

**Comment by dheerajd-msys** [comment]
One of test is passing with replacing fqdn to localhost https://buildkite.com/chef/chef-supermarket-master-omnibus-adhoc/builds/163#9e4f0f3b-53d2-42ca-afe0-b4dba9111630

**Comment by dheerajd-msys** [comment]
But this is again failing for all of 3 tests : https://buildkite.com/chef/chef-supermarket-master-omnibus-adhoc/builds/165#_

**Pull request merged**
