### PR TITLE
Change chef_tool to chef_infra_tool in model

### PR DESCRIPTION
**Pull request by msys-sgarg**
Signed-off-by: smriti <sgarg@msystechnologies.com>

On the UI tool type has to appear as Chef Infra Tool instead of Chef tool

## Description
In model class, in allowed types array for tool changed chef_tool to chef_infra_tool

## Related Issue
https://github.com/chef/supermarket/issues/1969

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by dheerajd-msys** [comment]
Looks Good!

**Comment by msys-sgarg** [comment]
@tas50 I think this change is good to be merged please check

**Comment by tas50** [comment]
Is this where we need to change it. The goal is just to make sure in the UI it shows up with the correct branding. how we store that on the backend doesn't really matter.

**Comment by msys-sgarg** [comment]
UI is referring to this datastructure we constructed in tool.rb to populate the dropdown. A change here will only reflect in backend.. A similar change was done as part of this PR https://github.com/chef/supermarket/pull/2036. There is only one place where we can make a change for update on UI in regards of `tools directory`

**Comment by dheerajd-msys** [comment]
Please rebase @msys-sgarg !!

**Comment by dheerajd-msys** [comment]
Closing this in favour of #2423

**Pull request closed without merging**
