### PR TITLE
Fixed redirection errors identified by Brakeman

### PR DESCRIPTION
**Pull request by RajeshPaul38**
Fixed vulnerable redirection errors by Brakeman. Added non vulnerabilities in brakeman ignore list.

Signed-off-by: Rajesh Paul <rajesh.paul@progress.com>

### Description

Have fixed the real vulnerabilities of redirection by adding only path instead of complete URL with host. Also identified the non vulnerabilities and added them to the Brakeman ignore list.

### Issues Resolved

[https://github.com/chef/supermarket/issues/2016](https://github.com/chef/supermarket/issues/2016)

### Check List

- [ ] New functionality includes tests
- [ ] All buildkite tests pass
- [ ] Full omnibus build and tests in buildkite pass
- [X] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Comment by tas50** [comment]
Gemfile.lock needs to be updated now that there's a new gem in it.

**Comment by RajeshPaul38** [comment]
@tas50 sure, let me add the gemfile.lock

**Comment by RajeshPaul38** [comment]
@tas50 I've added the Gemfile.lock.

**Comment by dheerajd-msys** [comment]
It requires DCO sign-off @RajeshPaul38

**Pull request merged**
