### PR TITLE
replace periodic job scheduler with one that is maintained

### LINKED ISSUE #1754: Celluloid is deprecated, git submodule missing, bundle install broken
```
➜  supermarket git:(master) bundle
Fetching gem metadata from https://rubygems.org/.........
Fetching https://github.com/rubysec/bundler-audit.git
Fetching https://github.com/celluloid/celluloid
Submodule 'culture' (http://github.com/celluloid/culture.git) registered for path 'culture'
Cloning into '/Users/rmoriz/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/celluloid-0d192022ffff/culture'...
remote: Repository not found.
fatal: repository 'https://github.com/celluloid/culture.git/' not found
fatal: clone of 'http://github.com/celluloid/culture.git' into submodule path '/Users/rmoriz/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/celluloid-0d192022ffff/culture' failed
Failed to clone 'culture'. Retry scheduled
```

Celluloid is unmaintained and its former maintainer decided to delete http://github.com/celluloid/culture from github. 

supermarket uses a hard coded ref of the `celluloid` repo that still contains a submodule reference to the now deleted submodule:

https://github.com/chef/supermarket/blob/master/src/supermarket/Gemfile#L17-L18

Looks like someone (Chef Software?) either needs to sponsor the Celluloid maintainer or remove the dependency: https://github.com/celluloid/celluloid/issues/779

### PR DESCRIPTION
**Pull request by robbkidd**
[sidetiq](https://github.com/endofunky/sidetiq) was heretofore our background job scheduler. It was deprecated a couple years ago, but still worked for Supermarket's purposes.

sidetiq required the use of celluloid which has also been deprecated. The version of celluloid require was old and required the use of a celluloid subcomponent that was brought in via git submodules.

There is much sadness in everything above this line.

[sidekiq-cron](https://github.com/ondrejbartas/sidekiq-cron) has been a go-to replacement for sidetiq in other projects since its maintainer declared it unmaintained. Here, we replace sidetiq with sidekiq-cron. This required:

* updated the Gemfile
* removing the require shenanigans for celluloid in application.rb
* setting the schedule for Supermarket's recurring jobs in the Sidekiq
  startup config in the initializer; putting in Sidekiq's startup
  prevents it from being called and attempting a write to Redis whenever
  the Rails app is initialized (e.g. precompiling assets, running tests,
  opening the console).
* removing the Sidetiq pieces from the scheduled jobs

The Jobs:

**SitemapRefreshWorker** was simple; remove Sidetiq things.

**OauthTokenRefreshScheduleWorker** was more invasive. sidekiq-cron does not have the same schedule backfill feature, so there is no last_occurence or current_occurence to work with. This job now assumes that it is run every five minutes to refresh any tokens. The querying of account with access tokens expiring soon moves to the Account class. This query gets to define what "soon" means. The job itself becomes much simpler by relying on this query and scheduling the token refresh for any account returned.

Fixes #1754

### CODE REVIEW

**Comment by robbkidd** [comment]
Note/question for myself: investigate what—if any—cleanup of Sidetiq's Redis keys would be necessary or appropriate.

**Comment by robbkidd** [comment]
⏲✅Moved the time-sensitive query to a query method on `Account` that takes a time to build the query's constraint around. Made repeatable testing possible again and simplified the code by putting concerns in more appropriate places.

😭➡️😂Moved the scheduling of jobs into Sidekiq's `configure_server` callback so that the scheduling of jobs (and therefore writes to Redis) are only attempted at a time that it would be reasonable to assume Redis is reachable.

**Comment by robbkidd** [comment]
This is green. I'll put on the backlog to maybe add a Rake task to clean up old sidetiq Redis keys, but it doesn't hurt anything to leave them.

READY FOR REVIEW 🎉

**Comment by robbkidd** [comment]
@pwelch @rmoriz :eyes:

**Comment by robbkidd** [comment]
@rmoriz I'll point out that I cherry-picked your commit with the rubyzip CVE exclusion. Thank you for that.

**Comment by rmoriz** [comment]
Thanks! please ping me when ready so I can rebase https://github.com/chef/supermarket/pull/1753

**Comment by rmoriz** [comment]
ping? @robbkidd

**Pull request merged**
