### PR TITLE
add QM pass rate percentage to search results, show page

### PR DESCRIPTION
**Pull request by robbkidd**
CookbookVersion now knows how to compute a version's pass rate percentage for quality metrics.

Add that display with a gauge to search results and on the Quality tab of the cookbook version display page.

### CODE REVIEW

**Comment by robbkidd** [comment]
## Search Results

screen shot 2017-10-03 at 11 47 45 am

## Cookbook Show Page (Quality tab)

screen shot 2017-10-03 at 11 53 15 am

**Comment by robbkidd** [comment]
@onlyhavecans 👀 📈

**Comment by robbkidd** [comment]
@hannah-radish Please don't cringe. 😬

**Comment by hannah-radish** [comment]
@robbkidd opening up a new branch from your branch to make some minor formatting edits

**Comment by onlyhavecans** [comment]
I love it as a first step! ✅

**Pull request merged**
