### PR TITLE
upgrade foodcritic to 11.2

### PR DESCRIPTION
**Pull request by robbkidd**
Because.

### CODE REVIEW

**Comment by robbkidd** [comment]
@tas50 Any reason to _not_ move to foodcritic 11.2? I'm distracted and so I'm unsure of the ramifications listed in the release notes.

**Comment by tas50** [comment]
We'll need to update the tags we use to any since 11.2 disabled the opensource tag.

**Comment by robbkidd** [comment]
So we add `opensource` to the existing:

```
FIERI_FOODCRITIC_TAGS="metadata,correctness,supermarket,portability,deprecated ~FC031"
```

... ?

**Comment by tas50** [comment]
Oh yes I forgot we have a curated list. We're good then

**Comment by tas50** [comment]
If we want to check for the opensource license yes

**Comment by robbkidd** [comment]
The one rule tagged with `opensource` at the moment is also tagged with `supermarket`, so we've opted to leave as is for the moment.

**Pull request merged**
