### PR TITLE
upgraded to ruby 3.1.0; made rubyracer gem conditional for mac

### PR DESCRIPTION
**Pull request by RajeshPaul38**
### Description

- Upgraded to ruby 3.1.0
- Made rubyracer gem conditional. Should not install for macOS.

### Issues Resolved

INFSUS-57

### Check List

- [ ] New functionality includes tests
- [ ] All buildkite tests pass
- [ ] Full omnibus build and tests in buildkite pass
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Comment by tas50** [comment]
We don't have an omnibus build of ruby 3.1 yet

**Comment by RajeshPaul38** [comment]
> We don't have an omnibus build of ruby 3.1 yet

Can we not have the support for the same in omnibus software? As 3.1 is the latest stable version of ruby, we are doing the changes in both supermarket and chef-manage with ruby version 3.1

CC @saghoshprogress

**Comment by tas50** [comment]
Neither of these projects can move to Ruby 3.1 until the packages team gets Ruby 3.1 building. It usually takes a while due to the large number of platforms and architectures we build on. It's blocking Workstation and Infra Client as well.

**Comment by RajeshPaul38** [comment]
> Neither of these projects can move to Ruby 3.1 until the packages team gets Ruby 3.1 building. It usually takes a while due to the large number of platforms and architectures we build on. It's blocking Workstation and Infra Client as well.

Okay. Thanks for the update.

**Pull request closed without merging**
