### PR TITLE
Add additional acceptable license strings

### LINKED ISSUE #1585: Correct list of licneses
`knife cookbook create bar -I apachev2` creates a cookbook with the following license:

`license          'Apache 2.0'`

The current quality metric allows for the SPDX version (`Apache-2.0`) and for the short license name passed as an argument to knife (`apachev2`) but does not currently allow for the license string generated by knife (`Apache 2.0`).

For now the quality metric should allow all both the arguments to knife (`apachev2, gplv2, gplv3, mit`) and the values that are generated based on those arguments:

* `Apache 2.0`
* `GNU Public License 2.0`
* `GNU Public License 3.0`
* `MIT`

### PR DESCRIPTION
**Pull request by nathenharvey**
Fixes #1585

Signed-off-by: Nathen Harvey <nharvey@chef.io>

### CODE REVIEW

**Comment by nathenharvey** [comment]
@robbkidd I realize I might be late to the discussion here.

**Comment by robbkidd** [comment]
@tas50 and I went back and forth on this and opted for SPDX in #1577. I think we both missed that the long versions come from knife, too. So, 👍 .

Do you think there is follow-on work that we should open a PR against the generator to use the SPDX license format? And then eventually circle back to this metric to reduce the list?

**Comment by tas50** [comment]
I didn't realize that knife was where those strings were coming from. I'm going to make sure that gets cleaned up in Chef 13.

**Comment by robbkidd** [comment]
Should we not also update the license metric definition to say these _three_ forms of strings are acceptable? Or leave the definition as is and remove the old style after Chef 13?

**Comment by tas50** [comment]
I'd prefer we actually get people on the right track here, but we need to get our tools generating the acceptable license string. We're all over the place right now in the worst possible way.

**Comment by robbkidd** [comment]
Ya. My current thinking is to allow these three styles until we've got the tools (knife, chef generate, foodcritic) all aligned and encouraging the SPDX format. Then we can _remove_ this code from Supermarket as the metric will be met by a new foodcritic rule in the supermarket category for open source licensing.

**Pull request merged**
