### PR TITLE
remove PR assignment

### LINKED ISSUE #1318: disable auto-assignment bot feature of curry
and by disable i may mean 'delete all the code'.

we're not using it, and its never been successfully used.

@thommay might still have plans for it, but at this point i think its more confusing to people than anything else...

### PR DESCRIPTION
**Pull request by lamont-granquist**
Closes #1318

### CODE REVIEW

**Comment by robbkidd** [comment]
<_bangs the set_> Travis, Y U NO test PR?

**Comment by robbkidd** [comment]
Expected error—the test for a PR to have an assignee after Curry PR annotation—when tests run locally on my machine.
```
  2) Curry::PullRequestAnnotator#annotate when all commit authors are authorized maintainers assigns a maintainer to a pull request
     Failure/Error: expect(pull_request.maintainer).to be(thom)

       expected #<User:70108749692340> => #<User id: 5, first_name: "Thom", last_name: "May", created_at: "2016-05-26 13:26:29", updated_at: "2016-05-26 13:26:29", company: nil, roles_mask: nil, email: "thom@example.com", jira_username: nil, irc_nickname: nil, twitter_username: nil, public_key: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQE...", install_preference: nil>
            got #<NilClass:8> => nil

       Compared using equal?, which compares object identity,
       but expected and actual are not the same object. Use
       `expect(actual).to eq(expected)` if you don't care about
       object identity in this example.
     # ./spec/models/curry/pull_request_annotator_spec.rb:296:in `block (6 levels) in <top (required)>'
     # ./.direnv/ruby/gems/vcr-2.9.2/lib/vcr/util/variable_args_block_caller.rb:9:in `call'
     # ./.direnv/ruby/gems/vcr-2.9.2/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # ./.direnv/ruby/gems/vcr-2.9.2/lib/vcr.rb:182:in `use_cassette'
     # ./spec/models/curry/pull_request_annotator_spec.rb:287:in `block (5 levels) in <top (required)>'
```

**Comment by robbkidd** [comment]
👍

**Comment by btm** [comment]
:+1:

**Pull request merged**
