### PR TITLE
Replace Librarian tab with Policyfile

### PR DESCRIPTION
**Pull request by tas50**
We should make it easier for users to cut and paste if using Policyfile

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by nathenharvey** [comment]
👍

**Comment by robbkidd** [comment]
@nellshamrell and I discussed this and we have concluded that it would be a better incremental change to _add_ Policyfile as an install preference and installation tab. I'll work on that today.

**Comment by robbkidd** [comment]
What a combined Berkshelf/Librarian/Policyfile tab could look like.

screen shot 2016-09-07 at 9 24 30 am

Eh ... Looks weird. But it's also a little weird to show the same install content across three separate tabs. Opinions?

**Comment by robbkidd** [comment]
With Policyfile as a separate tab to show declaring a source for the cookbook.

screen shot 2016-09-07 at 12 49 26 pm

**Comment by tas50** [comment]
👍

**Pull request merged**
