### PR TITLE
Updates for publishing licensing information

### PR DESCRIPTION
**Pull request by sersut**
This PR picks up the latest version of omnibus and omnibus-software which contains the required license information and the logic to publish this information to artifactory. After this change our download pages will be able to be updated to display the project specific license for supermarket.

/cc: @chef/engineering-services @chef/supermarket

### CODE REVIEW

**Comment by robbkidd** [comment]
Internal build test in progress.

**Comment by yzl** [comment]
👍  pending successful test build

**Comment by rhass** [comment]
I am not sure if this is something to be concerned about or not, but I just want to highlight it before this is merged:

https://travis-ci.org/chef/supermarket/builds/124252115#L656-L677

**Comment by sersut** [comment]
@rhass seems to me some warnings during the tests but @robbkidd will let us know if something we need to be concerned about for sure 😄

**Comment by robbkidd** [comment]
The warnings can be ignored for a little while because the karma tests _do_ get run. The configuration of the Rails apps' javascript integration tests got very grumpy after the app/omnibus repo consolidation. Travis' tester nodes appear to have a node install that works well enough. Getting rid of the warnings is on my TODO.

**Comment by rhass** [comment]
:+1:

**Comment by robbkidd** [comment]
Internal build passed testing 👍

**Comment by robbkidd** [comment]
Confirmed licensing for `expat` and `git` were not grumped about in the Supermarket build.

**Pull request merged**
