### PR TITLE
Enable FIPS for the Ubuntu builds

### PR DESCRIPTION
**Pull request by dheerajd-msys**
Signed-off-by: dheerajd-msys <dhsingh@progress.com>

### Description

This change enables FIPS onto Ubuntu builds

### Issues Resolved

Fixes https://github.com/chef/supermarket/issues/1956

### Check List

- [ ] New functionality includes tests
- [ ] All buildkite tests pass
- [ ] Full omnibus build and tests in buildkite pass
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [x] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Comment by tas50** [comment]
We will need to get the build working first so we can test this with an adhoc

**Comment by dheerajd-msys** [comment]
ok @tas50 Will check that then.

**Comment by dheerajd-msys** [comment]
Build https://buildkite.com/chef/chef-supermarket-master-omnibus-release/builds/125#17bcbeee-0208-4eab-b436-56ba128020c0 fails for the error `Supermarket::S3Config::IncompleteConfig: Got some, but not all, of the required S3 configs. Must provide ["S3_BUCKET", "S3_REGION"] to configure cookbook storage in an S3 bucket.`

**Comment by dheerajd-msys** [comment]
Adhoc build : https://buildkite.com/chef/chef-supermarket-master-omnibus-adhoc/builds/71#b1ea2f1e-9d1c-48ac-b65d-9192b95572d5

**Comment by dheerajd-msys** [comment]
Adhoc build https://buildkite.com/chef/chef-supermarket-master-omnibus-adhoc/builds/80#201c6fe5-f377-4d5f-baa7-c79b75fc9e17 resolves the error `yarn executable is not detected` for commit 1125d66e016428979e82c4d35276c88b5f13ff40 . Although it still fails while ```bundle exec rake assets:precompile```

**Comment by tas50** [comment]
the s3 stuff is fixed on master already if you rebase, but we should chat more about the creation of a verify pipeline and a bk script to get around the yarn issue. I'm curious why we can't just install yarn within the existing omnibus definitions.

**Comment by dheerajd-msys** [comment]
@tas50 Thanks for fixing yarn issue. I was only trying to fix this yarn issue but was not able to grab that we could do it in the way as you did so went ahead and wrote that bk script. Nevermind I am going to revert that for now.

**Comment by dheerajd-msys** [comment]
Adhoc build is successful but `supermarket-ctl test` are failing https://buildkite.com/chef/chef-supermarket-master-omnibus-adhoc/builds/95#_

**Comment by tas50** [comment]
the ctl commands are failing on the nodejs stuff still. I'm looking at getting a working nodejs install.

**Comment by tas50** [comment]
https://buildkite.com/chef/chef-supermarket-master-omnibus-adhoc/builds/138#f9c17ce8-1bde-41b0-80db-dd61387a9285

**Pull request merged**
