### PR TITLE
upgrade to Ruby 2.5.0

### PR DESCRIPTION
**Pull request by robbkidd**
Upgrade Ruby -> Upgrade Rubocop so that it knows about new Ruby -> handle a bunch of new Cops.

Are you going to upgrade Ruby? WHAT DOES IT LOOK LIKE I'M DOING!?!

To review, it's probably smoothest to walk the commits to break up the WALL OF CHANGES into how each Cop finding was addressed with commentary.

### CODE REVIEW

**Comment by scotthain** [comment]
Holy buckets.

**Comment by robbkidd** [comment]
> Holy buckets.

**Comment by robbkidd** [comment]
> Holy buckets.

@scotthain, is that approval, disapproval, or neutral dismay?

**Comment by scotthain** [comment]
@robbkidd sorry! That was amazement at the effort and how well organized and put together this PR is. Y'all did a killer job.

**Pull request merged**
