### PR TITLE
Migrate verification tests to Buildkite

### PR DESCRIPTION
**Pull request by jaymalasinha**
Signed-off-by: Jaymala Sinha <jsinha@chef.io>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by robbkidd** [comment]
As a part of this migration, there's some things being verified that I wish we could tear out. For example, the linting of the terraform stuff and anything to do with the supermarket-deploy cookbook. I'm 87% positive those aren't necessary anymore, but other folks would have to weigh in.

**Comment by robbkidd** [comment]
@jeremiahsnapp Any idea whether `cookbooks/supermarket-deploy`, `inspec/supermarket-smoke`, and `terraform` could be removed from the Supermarket project? Are the systems in the ACC pipeline still around? Are they used?

**Comment by robbkidd** [comment]
@jaymalasinha, is there any docker-inside-of-docker option on the buildkite builder for the verification steps? The project has [a `docker-compose.yml` that can spin up a PostgreSQL service and a Redis service](https://github.com/chef/supermarket/blob/cc49068bc4d2affff11b77939b61e0d2bd6f9a29/src/supermarket/docker-compose.yml) that works for test and development environments.

**Comment by tduffield** [comment]
We are going to delay this work at the moment. Closing the PR but we'll keep the branch alive for the time being. Will revisit sometime in the near future.

**Pull request closed without merging**
