### PR TITLE
Temporary urls for private s3 storage

### PR DESCRIPTION
**Pull request by nellshamrell**
Fix for #964

### CODE REVIEW

**Comment by jf647** [comment]
Is is possible to not lock the private buckets to setting the object ACL?

Our bucket configuration uses S3 bucket policies.  We cannot set the ACL of an object, and if you try the request is rejected with an access denied error.  We rely on policies to protect the objects.

**Comment by nellshamrell** [comment]
Looking into that now.

**Comment by nellshamrell** [comment]
Thanks for the feedback!

If I were to make setting the s3 permissions optional here:
```bash
    if ENV['S3_PRIVATE_URLS'].present?
      options = options.merge(
        s3_permissions: :private
      )
```
Perhaps by adding another environmental variable.
```bash
    if ENV['S3_PRIVATE_OBJECT_ACLS'].present?
      options = options.merge(
        s3_permissions: :private
      }
    end
```
If you were to leave the S3_PRIVATE_OBJECT_ACLS environmental variable as nil, and therefore the s3_permissions were not set so as not to conflict with your bucket policies, would this solve your issue?

You would still need to set the expire time for the url in the S3_PRIVATE_URLS_EXPIRE environmental variable (though I’ll probably rename it to something like S3_URLS_EXPIRE to be a bit clearer).  Then you would have expiring urls, but without setting the s3_permissions to private. 

Thank you!

**Comment by jf647** [comment]
Yes, that combination of environment variables would work.

Thanks

**Comment by nellshamrell** [comment]
Coding that up now :)

**Comment by nellshamrell** [comment]
The code changes are complete and tested.  Once the Travis CI build turns green, this is ready for review then merging!

**Comment by someara** [comment]
lgtm

**Comment by cwebberOps** [comment]
@leftathome Would love your thoughts on this PR, for, ummmm, reasons.

**Pull request merged**
