### PR TITLE
Update Ruby to 2.5.3

### PR DESCRIPTION
**Pull request by tas50**
This resolves 2 CVEs and multiple bugs

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by tas50** [comment]
Travis seems to be stuck

**Comment by robbkidd** [comment]
Cool. We broke it.

**Comment by robbkidd** [comment]
Turns out, our Travis builds were blocked for an unrelated reason. Therefore, I will resume my rebasing and force-pushing! Gonna merge'n'squash these and push back up to trigger a new Travis run.

force pushing never causes problems

**Comment by tas50** [comment]
@robbkidd This one passes in travis now

**Comment by robbkidd** [comment]
Yup! After I had help undoing "fixing" it yesterday.

**Pull request merged**
