### PR TITLE
karma devDependencies updated

### PR DESCRIPTION
**Pull request by pratixha**
Signed-off-by: pratixha <pratiksha.prajapati@msystechnologies.com>

### Description
    "karma": "~6.3.16",
    "karma-coffee-preprocessor": "^1.0.1",
    "karma-mocha": "^2.0.1",
    "karma-osx-reporter": "^0.2.1",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-requirejs": "^1.1.0",
    "karma-spec-reporter": "^0.0.33",
### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]

### Check List

- [ ] New functionality includes tests
- [ ] All buildkite tests pass
- [ ] Full omnibus build and tests in buildkite pass
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Comment by pratixha** [comment]
Buildkite :- https://buildkite.com/chef/chef-supermarket-main-omnibus-adhoc/builds/436

**Review by RajeshPaul38 — APPROVED** [review]
Looks good

**Comment by RajeshPaul38** [comment]
Ready to merge @saghoshprogress

**Comment by RajeshPaul38** [comment]
Ready for merge @saghoshprogress

**Review by RoyShravani — APPROVED** [review]

**Review by msys-sgarg — APPROVED** [review]
Looks good to me

**Pull request merged**
