### PR TITLE
fix dependabot PRs

### PR DESCRIPTION
**Pull request by dheerajd-msys**
### Description

-- Fix dependabot PRs

### Check List

- [ ] New functionality includes tests
- [x] All buildkite tests pass
- [x] Full omnibus build and tests in buildkite pass
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [x] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Review by msys-sgarg — APPROVED** [review]
looks good to me

**Review by antima-gupta — COMMENTED** [review]
@dheerajd-msys Please fix the lint errors.

**Comment by RajeshPaul38** [comment]
Needs lint fix @dheerajd-msys

**Comment by dheerajd-msys** [comment]
Adhoc build : https://buildkite.com/chef/chef-supermarket-main-omnibus-adhoc/builds/344

**Comment by antima-gupta** [comment]
@dheerajd-msys Please rebase this branch.

**Review by saghoshprogress — APPROVED** [review]

**Comment by dheerajd-msys** [comment]
This PR duplicates https://github.com/chef/supermarket/pull/2523 so deleting this.

**Pull request closed without merging**
