### PR TITLE
ROR Upgrade - Ruby 3 / Rails 7

### PR DESCRIPTION
**Pull request by RajeshPaul38**
### Description

[Please describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]

### Check List

- [ ] New functionality includes tests
- [ ] All buildkite tests pass
- [ ] Full omnibus build and tests in buildkite pass
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Comment by dheerajd-msys** [comment]
Please check the conflicts @RajeshPaul38

**Comment by RajeshPaul38** [comment]
Build link: https://buildkite.com/chef/chef-supermarket-main-omnibus-adhoc/builds/375
In progress.

**Comment by RajeshPaul38** [comment]
Build is green

> Build link: https://buildkite.com/chef/chef-supermarket-main-omnibus-adhoc/builds/503

**Comment by msys-sgarg** [comment]
Please resolve conflicts then we are good to go i think

**Comment by RajeshPaul38** [comment]
> Please resolve conflicts then we are good to go i think

Merge conflicts resolved. Pls proceed

**Review by saghoshprogress — APPROVED** [review]

**Pull request merged**
