### PR TITLE
zLinux platform

### PR DESCRIPTION
**Pull request by jjasghar**
Adding zLinux platform to Supermarket

### CODE REVIEW

**Comment by jjasghar** [comment]
I took inspiration from: https://github.com/chef/supermarket/pull/968

**Comment by robbkidd** [comment]
Sadly that PR also involved generating an icon font. In consultation with the other front-end developers at Chef, I think we're moving away from icon fonts unless it is discovered that our SVG icons are truly slowing down page loads. So, we'll need to untangle platform icon display from the icon font in this PR.

**Comment by robbkidd** [comment]
That's the new SVG on the end, there. screen shot 2016-04-08 at 6 59 09 pm

**Comment by robbkidd** [comment]
We probably should remove some of [the font-icon stuff from the SCSS](https://github.com/chef/supermarket/blob/181f1293dfc8f496fdb218939a3db31bfb9c129f/src/supermarket/app/assets/stylesheets/cookbooks/platform_icons.scss#L16-L20), too.

**Comment by nellshamrell** [comment]
:+1:

**Comment by jjasghar** [comment]
Huuuzzahh!

**Pull request merged**
