### PR TITLE
Bring omnibus packager into main repo

### LINKED ISSUE #1254: The Great Repo Consolidation
# Goal

Produce the Supermarket (omnibus) package from a single repository.

# Why?

The Supermarket codebase is managed in many repositories:
* chef/supermarket
* chef/omnibus-supermarket
* chef-cookbooks/supermarket-omnibus-cookbook
* chef/fieri
* chef-cookbooks/fieri

This makes tracking issues and code changes to solve them difficult as effort is spread across multiple repos. To produce a single system, we'll be consolidating some or all of the various supermarket-related repositories into `chef/supermarket`.

## To Do

- [x] make a todo list
- [x] move `chef/supermarket` Rails app root to `src/`
- [x] import git history of `chef/omnibus-supermarket` into `chef/supermarket` in a new `omnibus` directory
- [x] update omnibus software definition for supermarket source location
- [x] confirm packaging excludes development temp files and configs
- [x] move to static versioning of the supermarket omnibus project (bump that like we used to do the software def tag reference)
- [x] update Travis build steps
- [x] update Gemnasium ?

## Work punted to other Issues
- automatic patch-version bumping #1257 
- update Code Climate #1258 low priority, may break it (or make grades look bad) and add as a fixme
- update Inch CI #1259 low priority, doc coverage checker - unsure how to get it to scan a subdir

### PR DESCRIPTION
**Pull request by robbkidd**
Merge in the omnibus-supermarket repo and history in effort towards a complete product repo, build pipeline, and acceptance environment.

Closes #1254

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by robbkidd** [comment]
Current error after making the adjustments in b9c65e8:
```
[Builder: supermarket] W | [5/5] Failed to execute command. Retrying in 160 seconds...
             [Builder: supermarket] I | Environment:
             [Builder: supermarket] I |   CFLAGS="-I/opt/supermarket/embedded/include -O2"
             [Builder: supermarket] I |   CPPFLAGS="-I/opt/supermarket/embedded/include -O2"
             [Builder: supermarket] I |   CXXFLAGS="-I/opt/supermarket/embedded/include -O2"
             [Builder: supermarket] I |   LDFLAGS="-Wl,-rpath,/opt/supermarket/embedded/lib -L/opt/supermarket/embedded/lib"
             [Builder: supermarket] I |   LD_RUN_PATH="/opt/supermarket/embedded/lib"
             [Builder: supermarket] I |   PATH="/opt/supermarket/bin:/opt/supermarket/embedded/bin:/home/vagrant/.gem/ruby/2.1.5/bin:/usr/local/bin:/opt/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/bin:/opt/rubies/ruby-2.1.5/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
             [Builder: supermarket] I |   PKG_CONFIG_PATH="/opt/supermarket/embedded/lib/pkgconfig"
             [Builder: supermarket] I | $ /opt/supermarket/embedded/bin/bundle install --jobs 3 --retry 3 --path=vendor/bundle --without development
             [Builder: supermarket] I | bundle `install --jobs 3 --retry 3 --path=vendor/bundle --without development': 310.8542s
             [Builder: supermarket] I | Build supermarket: 310.8563s
The following shell command exited with status 1:

    $ CFLAGS=-I/opt/supermarket/embedded/include 
        -O2 CPPFLAGS=-I/opt/supermarket/embedded/include 
        -O2 CXXFLAGS=-I/opt/supermarket/embedded/include 
        -O2 LDFLAGS=-Wl,-rpath,/opt/supermarket/embedded/lib
        -L/opt/supermarket/embedded/lib LD_RUN_PATH=/opt/supermarket/embedded/lib
PATH=/opt/supermarket/bin:/opt/supermarket/embedded/bin:/home/vagrant/.gem/ruby/2.1.5/bin:/usr/local/bin:/opt/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/bin:/opt/rubies/ruby-2.1.5/bin:/usr/bin:/usr/local/sbin:/usr/sbin 
PKG_CONFIG_PATH=/opt/supermarket/embedded/lib/pkgconfig
        /opt/supermarket/embedded/bin/bundle install --jobs 3 --retry 3 --path=vendor/bundle --without development

Output:

    (nothing)

Error:

    /home/vagrant/.gem/ruby/2.1.5/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:183:in `chdir': No
 such file or directory @ dir_chdir - /var/cache/omnibus/src/supermarket (Errno::ENOENT)
```

**Comment by robbkidd** [comment]
The grumpy Curry bot has seen at least one commit in this merged history from `smith@getchef.com` who is @smith and _is_ authorized to contribute. The warning shall be summarily ignored.

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by robbkidd** [comment]
Holy schneikies, I think this is ready for review.

@nellshamrell @schisamo @yzl @ksubrama :eyes: ?

**Comment by robbkidd** [comment]
I notice with the change from `source git:` to `source path:` that my not-tagged package version has gone from `2.5.0+20160331200453` format to `2.5.0+20160331200453.git.228.b9c65e8`. Is that a change in omnibus in the last ~30 days or a change in how the package version is computed?

**Comment by schisamo** [comment]
@robbkidd Previously the version for your package was pulled from the `supermarket` software def's code checkout and computed using `git describe`. Since you were always pegged to an exact tag of the rails app `git describe` returned the tag only, now that you are not on an exact tag you are seeing the extended `git describe` data. I recommend moving to a static build version in your project definition. So in `omnibus/config/project/supermarket.rb` you want a line like:

```ruby
build_version   "MAJOR.MINOR.PATCH"
```

You would change this when appropriate. Another approach teams have used is to have a `VERSION` in the root of the repo that various code components (including the omnbius code) read for the version. If you had something like that you could read it in the omnibus project def like:

```ruby
current_file ||= __FILE__
version_file = File.expand_path("../../../../VERSION", current_file)
build_version IO.read(version_file).strip
```

You could then have the Rails app reach this `VERSION` file also to determine a version to display in the footer or some other appropriate place.

**Comment by nellshamrell** [comment]
:rocket: :cake:

**Comment by robbkidd** [comment]
Turning the key! :key:

**Pull request merged**
