### PR TITLE
Upgrade from Rails 4.1 to 4.2

### PR DESCRIPTION
**Pull request by robbkidd**
There are a couple remaining issues not covered currently by our tests:

- [x] Can't migrate from a new database. We've got [an index created by a migration from 2014](https://github.com/chef/supermarket/blob/2032d961a31f5b21cca6e4b2177b5a4f2f6be097/src/supermarket/db/migrate/20140206202928_create_curry_unknown_pull_request_committer_table.rb#L5) that generates a name for the index that is too long. ActiveRecord apparently only started erroring on that in 4.2. `db:schema:load` works which is why Travis is passing.
- [x] Rails 4.2 doesn't like [what we're doing to create cookbooks with cookbook versions](https://github.com/chef/supermarket/blob/2032d961a31f5b21cca6e4b2177b5a4f2f6be097/src/supermarket/db/seeds.rb#L252-L264) in db/seeds.rb. Because the cookbook isn't saved yet, the cookbook_version's `first_or_create` fails.

### CODE REVIEW

**Comment by robbkidd** [comment]
For the migration, I did this as a quick fix in my dev environment:

```diff
@@ -2,7 +2,7 @@ class CreateCurryUnknownPullRequestCommitterTable < ActiveRecord::Migration
   def change
     create_table :curry_unknown_pull_request_committers do |t|
       t.integer :pull_request_id, index: true, null: false
-      t.integer :unknown_committer_id, index: true, null: false
+      t.integer :unknown_committer_id, index: {name: 'curry_unknown_pull_request_committers_unknown_committer_id'}, null: false
     end
   end
 end
```

That brings the index name down below 64 characters.

The resulting `db/schema.rb` has a change for _all_ tables, though:

```diff
@@ -17,7 +17,7 @@ ActiveRecord::Schema.define(version: 20160616180001) do
   enable_extension "plpgsql"
   enable_extension "pg_trgm"

-  create_table "accounts", force: true do |t|
+  create_table "accounts", force: :cascade do |t|
```

[Rails 4.2 release notes mention](http://edgeguides.rubyonrails.org/4_2_release_notes.html#active-record-notable-changes) that this is: 

> SchemaDumper uses force: :cascade on create_table. This makes it possible to reload a schema when foreign keys are in place.

I suspect this may be OK.

**Comment by robbkidd** [comment]
Fun with migrations.

The table `curry_unknown_pull_request_committers` is [renamed](https://github.com/chef/supermarket/blob/2032d961a31f5b21cca6e4b2177b5a4f2f6be097/src/supermarket/db/migrate/20140214190513_rename_unknown_pull_request_committers_to_pull_request_commit_authors.rb) a few migrations later to `curry_pull_request_commit_authors`. Indexes that follow the Rails naming conventions also get renamed, but those that don't match are left as is.

```
supermarket_development=# \d curry_pull_request_commit_authors
                              Table "public.curry_pull_request_commit_authors"
      Column      |  Type   |                                   Modifiers
------------------+---------+--------------------------------------------------------------------------------
 id               | integer | not null default nextval('curry_pull_request_commit_authors_id_seq'::regclass)
 pull_request_id  | integer | not null
 commit_author_id | integer | not null
Indexes:
    "curry_pull_request_commit_authors_pkey" PRIMARY KEY, btree (id)
    "curry_pr_commit_author_ids" UNIQUE, btree (commit_author_id, pull_request_id)
    "idx_curry_unk_pull_request_committers_unk_committer_id" btree (commit_author_id)
    "index_curry_pull_request_commit_authors_on_pull_request_id" btree (pull_request_id)
```

Note that `idx_curry_unk_pull_request_committers_unk_committer_id` is the name I overrode in the quick fix. The other `index_curry_pull_request_commit_authors_on_pull_request_id` got renamed but the `rename_table` so that the index name would match the table it is indexing.

I'm pleased to see confirmation that the misnamed index is still tracking the correct column after `unknown_committer_id` was renamed to `commit_author_id`. Thanks, PostgreSQL!

**Comment by robbkidd** [comment]
Potential solution:

1. Set the index name to something short in the migration that creates the table.
2. When the table is renamed later, rename the short index name to one that follows the Rails convention.

Subsequent changes to the table (like a column rename) are then picked up and applied to the index.

```diff
diff --git a/src/supermarket/db/migrate/20140206202928_create_curry_unknown_pull_request_committer_table.rb b/src/supermarket/db/migrate/20140206202928_create_curry_unknown_pull_request_committer_table.rb
index 1794fed..7fd1dcc 100644
--- a/src/supermarket/db/migrate/20140206202928_create_curry_unknown_pull_request_committer_table.rb
+++ b/src/supermarket/db/migrate/20140206202928_create_curry_unknown_pull_request_committer_table.rb
@@ -2,7 +2,7 @@ class CreateCurryUnknownPullRequestCommitterTable < ActiveRecord::Migration
   def change
     create_table :curry_unknown_pull_request_committers do |t|
       t.integer :pull_request_id, index: true, null: false
-      t.integer :unknown_committer_id, index: true, null: false
+      t.integer :unknown_committer_id, index: {name: 'idx_curry_unk_pull_request_committers_unk_committer_id'}, null: false
     end
   end
 end
diff --git a/src/supermarket/db/migrate/20140214190513_rename_unknown_pull_request_committers_to_pull_request_commit_authors.rb b/src/supermarket/db/migrate/20140214190513_rename_unknown_pull_request_committers_to_pull_request_commit_authors.rb
index 5e2ffa5..eea20b9 100644
--- a/src/supermarket/db/migrate/20140214190513_rename_unknown_pull_request_committers_to_pull_request_commit_authors.rb
+++ b/src/supermarket/db/migrate/20140214190513_rename_unknown_pull_request_committers_to_pull_request_commit_authors.rb
@@ -1,5 +1,7 @@
 class RenameUnknownPullRequestCommittersToPullRequestCommitAuthors < ActiveRecord::Migration
   def change
     rename_table :curry_unknown_pull_request_committers, :curry_pull_request_commit_authors
+    rename_index :curry_pull_request_commit_authors, 'idx_curry_unk_pull_request_committers_unk_committer_id',
+      'index_curry_pull_request_commit_authors_on_unknown_committer_id'
   end
 end
```

Results in:

```
supermarket_development=# \d curry_pull_request_commit_authors
                              Table "public.curry_pull_request_commit_authors"
      Column      |  Type   |                                   Modifiers
------------------+---------+--------------------------------------------------------------------------------
 id               | integer | not null default nextval('curry_pull_request_commit_authors_id_seq'::regclass)
 pull_request_id  | integer | not null
 commit_author_id | integer | not null
Indexes:
    "curry_pull_request_commit_authors_pkey" PRIMARY KEY, btree (id)
    "curry_pr_commit_author_ids" UNIQUE, btree (commit_author_id, pull_request_id)
    "index_curry_pull_request_commit_authors_on_commit_author_id" btree (commit_author_id)
    "index_curry_pull_request_commit_authors_on_pull_request_id" btree (pull_request_id)
```

Which has those two declared indexes named according to convention for the up-to-date names of the table and its columns.

**Comment by robbkidd** [comment]
"But Robb, what's it look like in production, though?" I hear you ask. Good question.

Staging:

```
supermarket_production=> \d curry_pull_request_commit_authors
                              Table "public.curry_pull_request_commit_authors"
      Column      |  Type   |                                   Modifiers
------------------+---------+--------------------------------------------------------------------------------
 id               | integer | not null default nextval('curry_pull_request_commit_authors_id_seq'::regclass)
 pull_request_id  | integer | not null
 commit_author_id | integer | not null
Indexes:
    "curry_unknown_pull_request_committers_pkey" PRIMARY KEY, btree (id)
    "curry_pr_commit_author_ids" UNIQUE, btree (commit_author_id, pull_request_id)
```

😿  Those two indexes are missing.

**Comment by robbkidd** [comment]
Freshly installed 2.8.2 in a TK VM does not have those indexes either:

```
supermarket=# \d curry_pull_request_commit_authors
                              Table "public.curry_pull_request_commit_authors"
      Column      |  Type   |                                   Modifiers
------------------+---------+--------------------------------------------------------------------------------
 id               | integer | not null default nextval('curry_pull_request_commit_authors_id_seq'::regclass)
 pull_request_id  | integer | not null
 commit_author_id | integer | not null
Indexes:
    "curry_pull_request_commit_authors_pkey" PRIMARY KEY, btree (id)
    "curry_pr_commit_author_ids" UNIQUE, btree (commit_author_id, pull_request_id)
```

**Comment by robbkidd** [comment]
Oh, indexes. You're so silly.

I think the indexes that exist in my dev database that do not exist in production are indexes that Rails 4.2 is of the opinion should exist. These new indexes are generated during a `db:migrate` with 4.2:

```
git show | grep "+  add_index"
+  add_index "accounts", ["uid"], name: "index_accounts_on_uid", using: :btree
+  add_index "accounts", ["username"], name: "index_accounts_on_username", using: :btree
+  add_index "cclas", ["version"], name: "index_cclas_on_version", using: :btree
+  add_index "curry_pull_request_commit_authors", ["commit_author_id"], name: "index_curry_pull_request_commit_authors_on_commit_author_id", using: :btree
+  add_index "curry_pull_request_commit_authors", ["pull_request_id"], name: "index_curry_pull_request_commit_authors_on_pull_request_id", using: :btree
+  add_index "curry_pull_requests", ["repository_id"], name: "index_curry_pull_requests_on_repository_id", using: :btree
+  add_index "iclas", ["version"], name: "index_iclas_on_version", using: :btree
```

This is a bit new to me. My current potentially-bad-idea is to include a migration with this update to `schema.rb` that checks for whether these indexes exist and creates them if not. I think that would keep current production databases inline with the new schema. I'm researching if this is a Known Thing.

**Comment by nellshamrell** [comment]
This seems reasonable!  I suggest we
1) Make a copy of the prod DB
2) Spin up a new prod environment - connecting it to the DB copy
3) Test the migrations on that
4) Run smoke tests on the new prod environment, evaluate whether anything appears to have broken

**Comment by nellshamrell** [comment]
👍 We have tested this thoroughly and it looks good!

**Comment by robbkidd** [comment]
👍 Works in a freshly built environment with a copy of production DB. Database migration went well taking maybe 10-20 seconds to create the new indexes.

**Pull request merged**
