### PR TITLE
Enable Chef/Security and InSpec/Deprecation cops

### PR DESCRIPTION
**Pull request by tas50**
We want to scan for these as well

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Review by antima-gupta — COMMENTED** [review]
Unit test is failing.

**Review by RajeshPaul38 — APPROVED** [review]
Looks Good

**Comment by RoyShravani** [comment]
We need to fix the unit tests.

**Comment by RoyShravani** [comment]
We need to resolve the merge conflicts.

**Comment by tas50** [comment]
@RoyShravani conflicts resolved

**Comment by ayushbhatt29** [comment]
Fieri unit test are failing.

**Review by RajeshPaul38 — APPROVED** [review]
LGTM syntax wise

**Comment by RajeshPaul38** [comment]
Fieri test failures need to be checked @tas50

**Comment by pratixha** [comment]
https://buildkite.com/chef/chef-supermarket-main-omnibus-adhoc/builds/424

**Review by dheerajd-msys — APPROVED** [review]
Looks good!!

**Pull request merged**
