### PR TITLE
Removed gem: ruby-filemagic; replaced with built in ruby module: IO

### LINKED ISSUE #2320: Investigate if we can move off ruby-filemagic
We are currently using https://github.com/blackwinter/ruby-filemagic to determine if uploaded files are gzip type. This project is unmaintained and requires libmagic which we probably want to avoid due to licensing concerns: https://github.com/wakingrufus/libmagic/blob/master/LICENSE

We probably want to move to https://github.com/rails/marcel

### PR DESCRIPTION
**Pull request by RajeshPaul38**
### Description

Removed gem: ruby-filemagic
Replaced with built in ruby module: IO

### Issues Resolved

#2320 

### Check List

- [x] New functionality includes tests
- [x] All buildkite tests pass
- [x] Full omnibus build and tests in buildkite pass
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Comment by RajeshPaul38** [comment]
Build: https://buildkite.com/chef/chef-supermarket-main-omnibus-adhoc/builds/284

**Comment by RajeshPaul38** [comment]
Build: https://buildkite.com/chef/chef-supermarket-main-omnibus-adhoc/builds/289

**Review by dheerajd-msys — APPROVED** [review]
Looks Good!!

**Comment by RajeshPaul38** [comment]
Have tested cookbook upload functionality. Moving out of WIP

**Review by saghoshprogress — APPROVED** [review]

**Pull request merged**
