### PR TITLE
Removed supported platforms metric

### PR DESCRIPTION
**Pull request by pratixha**
Removed supported platforms metric from supermarket code 

https://github.com/chef/supermarket/issues/2184

### Check List

- [x] New functionality includes tests
- [x] All buildkite tests pass
- [x] Full omnibus build and tests in buildkite pass
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [x] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Comment by RajeshPaul38** [comment]
@pratixha is this WIP or ready for review? If ready, remove the WIP text from title. Also fix the lint error as highlighted by chefstyle action.

**Comment by RajeshPaul38** [comment]
@pratixha pls attach a buildkite link and update the status after build completion.

**Comment by RajeshPaul38** [comment]
Looks good from code perspective.

**Comment by msys-sgarg** [comment]
https://buildkite.com/chef/chef-supermarket-main-omnibus-adhoc/builds/360 - Successful build

**Review by msys-sgarg — APPROVED** [review]
Looks good to me

**Comment by dheerajd-msys** [comment]
DCO sign off is missing @pratixha

**Review by RoyShravani — APPROVED** [review]

**Review by RajeshPaul38 — APPROVED** [review]
LGTM

**Comment by RajeshPaul38** [comment]
This PR has 3 approvals. We should merge this @saghoshprogress

**Pull request merged**
