### PR TITLE
Remove the Ruby 2.1.3 pin from the Gemfile, because we're already pinning it in omnibus-supermarket

### PR DESCRIPTION
**Pull request by irvingpop**
Also update `:github` lines in the Gemfile to use https instead.

### CODE REVIEW

**Comment by smith** [comment]
We should pin the same version that we do in Omnibus, so that we run the same version in dev as in prod.

:+1: to changing this to be the same as what we're shipping in Omnibus, :-1: to removing it from here.

**Comment by irvingpop** [comment]
hey @smith how about something like this, to satisfy both the Omnibus and your current local dev use cases:
```ruby
ruby ENV['CUSTOM_RUBY_VERSION'] || '2.1.3'
```

and maybe a `TODO` comment above it stating that this value needs to be updated as local dev changes, and removed when local dev doesn't need to specify it anymore?

**Comment by smith** [comment]
> hey [@smith](https://github.com/smith) how about something like this, to satisfy both the Omnibus and your current local dev use cases:

> ruby ENV['CUSTOM_RUBY_VERSION'] || '2.1.3'
> and maybe a `TODO` comment above it stating that this value needs to be updated as local dev changes, and removed when local dev doesn't need to specify it anymore?

That sounds like it makes things more complex and I don't see what benefit it would have. Let's just remove it and link to the omnibus override line in the Gemfile and/or README.

**Comment by irvingpop** [comment]
@smith done! :)

**Comment by nellshamrell** [comment]
:+1:

**Pull request merged**
