### PR TITLE
Remove git dependency

### PR DESCRIPTION
**Pull request by dheerajd-msys**
Signed-off-by: Dheeraj Singh Dubey <dhsingh@progress.com>

### Description

-- Remove git dependency
### Issues Resolved

Fixes : #1959 

### Check List

- [ ] New functionality includes tests
- [x] All buildkite tests pass
- [x] Full omnibus build and tests in buildkite pass
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [x] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Comment by dheerajd-msys** [comment]
Green adhoc build https://buildkite.com/chef/chef-supermarket-main-omnibus-adhoc/builds/306

**Comment by dheerajd-msys** [comment]
Need to check that, will update here

**Comment by dheerajd-msys** [comment]
Yes @tas50 they are working as expected, Please check and confirm.

Screenshot 2022-02-14 at 3 13 55 PM

**Comment by sanga1794** [comment]
Looks good to me.

**Review by pratixha — APPROVED** [review]

**Review by saghoshprogress — APPROVED** [review]

**Pull request merged**
