### PR TITLE
set runit cookbook version equal or greater than the version a bug fix appears in

### PR DESCRIPTION
**Pull request by nellshamrell**
Signed-off-by: Nell Shamrell <nellshamrell@gmail.com>

### CODE REVIEW

**Comment by robbkidd** [comment]
I have tested this change with a locally-built omnibus package and it fixes the nginx running with the right config problem.

I'm torn between:

* unpinning which should work for CI because we don't check in `Berksfile.lock`, but could have unexpected results in local builds
* setting runit version to `>= 3.0.3` to ensure a build (local or CI) uses a version without the bug

**Comment by nellshamrell** [comment]
Let's go ahead and pin to >= 3.0.3, since we know that will avoid the bug. Making that change now.

**Comment by robbkidd** [comment]
`git squoosh`?

**Comment by nellshamrell** [comment]
Squoosh done

**Pull request merged**
