### PR TITLE
Upgrade to Ruby 2.1.7

### PR DESCRIPTION
**Pull request by robbkidd**
This will probably be a multi-part process:

- [x] add 2.1.7 to the Travis build matrix
- [x] confirm app unit tests pass under 2.1.7
- [ ] update Ruby version in [omnibus-supermarket](https://github.com/chef/omnibus-supermarket/blob/master/config/projects/supermarket.rb#L33)
- [ ] confirm upgrade in omnibus passes through CI
- [ ] update README here for Ruby version requirement

### CODE REVIEW

**Comment by smith** [comment]
:+1: 

Why not 2.2?

**Comment by robbkidd** [comment]
Baby steps? :smile:

I'll do a test run in my dev environment with 2.2 and if that's happy, sure, add it to the build matrix.

**Comment by robbkidd** [comment]
```
warning: you are loading parser/ruby22 from .rvm/gems/ruby-2.2.3@supermarket/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'.
warning: Ruby 2.2 is not released yet and parser support may be incomplete.
```
Hello, yak hole.

**Comment by robbkidd** [comment]
OK. Switching to try to upgrade to Ruby 2.2.3 given a weird segfault we get on the RHEL5 builder. (Same as described in [Compile error on CentOS: Segmentation fault after "linking miniruby"](https://redmine.ruby-lang.org/issues/11602) Ruby issue.)

Updating this PR title and description to target 2.2.3. Ignore the version I included in the branch name. :grimacing:

**Comment by robbkidd** [comment]
Hmm. Instead, I'll open a new PR with a new branch.

**Pull request closed without merging**
