### PR TITLE
add instructions for testing and running quality metrics

### LINKED ISSUE #1536: doc update for running quality metrics in dev environment

### PR DESCRIPTION
**Pull request by robbkidd**
Includes some cleanup of feature flags in the main README

Closes #1536

### CODE REVIEW

**Comment by robbkidd** [comment]
@nellshamrell While writing, I opted to shorten the list of ways further to keep the choices simpler. I can add some or all back in if you think that'd be better, or we can add them later if we find the current options limiting.

**Comment by nellshamrell** [comment]
Should we include the ctl commands as well?

**Comment by robbkidd** [comment]
I _could_, but the original scope of the documentation task was to facilitate contributions. So it was to help people run them in the development environment so that they could contribute more metrics code. The -ctl commands aren't available in dev.

**Comment by nellshamrell** [comment]
Good point.  I'll add a separate issue to document the ctl commands.

**Comment by nellshamrell** [comment]
This looks good!

**Pull request merged**
