### PR TITLE
Add support for enabling Server Side Encryption when storing cookbooks in AWS S3

### PR DESCRIPTION
**Pull request by bdwyertech**
## Description
Adds support for explicitly configuring S3 Server Side Encryption.  Paperclip has supported this since ~2012.

## Related Issue
https://chef-software.ideas.aha.io/ideas/SH-I-82

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by robbkidd** [comment]
Thank you for this pull request, @bdwyertech! I am investigating ways to automate testing this behavior.

**Comment by robbkidd** [comment]
@bdwyertech I did a little overhaul to the Paperclip configuration to test that we're producing a "correct" hash for Paperclip. I've confirmed in a test environment that [the addition of `:s3_server_side_encryption` to the config](https://github.com/chef/supermarket/pull/1888/files#diff-7dcf17cc6f3ab6852e71f207ceba986fR45-R47) does add a `"X-Amz-Server-Side-Encryption": "AES256"` header to the PUT requests to the S3 endpoint. After that point, I think we can choose to trust that AWS does what it says it does.

**Comment by bdwyertech** [comment]
Cool dibs, I am fairly certain that with bucket default settings adjusted, we'd be "supporting" encrypted buckets anyway, but for audit purposes, better to have it explicitly enabled

**Review by robbkidd — APPROVED** [review]
tenor-70148255

**Comment by robbkidd** [comment]
Released in 3.3.35 (stable channel) and 3.3.34 (current channel).

**Comment by bdwyertech** [comment]
Thank you very much for the expedience @robbkidd

**Pull request merged**
