### PR TITLE
Fix GitHub webhook creation for Curry subscribing to a repo

### PR DESCRIPTION
**Pull request by robbkidd**
Move Curry's GitHub callback to RepositorySubscriber
* RepositorySubscriber is the only thing that needs to know how to compute
  what the callback_url should be.
* The callback_url for the Curry webhook should almost always include the
  public domain for the supermarket site. Compute it with the Rails
  url_helper for the `curry/pull_request_updates` controller with the
  runtime domain config.
* Remove the ability to override via ENV and handle test environment.

Change to bang-methods to communicate unexpected state changes

* `subscribe!` saves a Curry::Repository and changes webhooks on the repo
  at GitHub
* `unsubscribe!` destroys both the repo's GitHub webhook and the
  Curry::Repository itself

State changes outside of `save` and `destroy` methods worthy of a `!`

### TODO
- [x] add back the ability to override the callback in a Rails environment (but omit setting a default in `.env`)
- [x] add a `resubscribe!` method that removes the webhook in a repo that matches saved `callback_url` and then subscribe with the current system `pubsubhubbub_callback_url`

### CODE REVIEW

**Comment by robbkidd** [comment]
Missed specs. Workin' on it.

**Comment by robbkidd** [comment]
An example of the `resubscribe!`.

Let's load up a curried repo, get an Octokit client to interrogate GitHub, and look at the repo's current webhooks.

```
» repo = Curry::Repository.first
  Curry::Repository Load (0.8ms)  SELECT  "curry_repositories".* FROM "curry_repositories"   ORDER BY "curry_repositories"."id" ASC LIMIT 1
=> #<Curry::Repository id: 1, owner: "chef", name: "paprika", created_at: "2015-11-25 20:05:27", updated_at: "2015-11-25 20:05:27", callback_url: "http://example.com">

» require 'octokit'
=> true
» client = Octokit::Client.new(access_token: ENV['GITHUB_ACCESS_TOKEN'])
=> #<Octokit::Client:0x3fdbcdb27260>

» client.hooks(repo.full_name).map {|hook| hook[:config][:url]}
=> ["http://currybowl.herokuapp.com/52f2934cec5edd0002000015",
 "https://chefio.atlassian.net/rest/bitbucket/1.0/repository/1118/sync",
 "https://chefio.atlassian.net/rest/bitbucket/1.0/repository/1118/sync"]
```

OK. 3 webhooks. Let's subscribe my development instance of Supermarket.

```
» subscriber = Curry::RepositorySubscriber.new repo
=> #<Curry::RepositorySubscriber:0x007fb79b4954d0
 @repository=
  #<Curry::Repository id: 1, owner: "chef", name: "paprika", created_at: "2015-11-25 20:05:27", updated_at: "2015-11-25 20:05:27", callback_url: "http://example.com">>

» subscriber.subscribe!
   (0.3ms)  BEGIN
  SQL (0.4ms)  UPDATE "curry_repositories" SET "callback_url" = $1, "updated_at" = $2 WHERE "curry_repositories"."id" = 1  [["callback_url", "http://localhost:3000/curry/pull_request_updates"], ["updated_at", "2015-12-02 01:18:08.395090"]]
   (1.0ms)  COMMIT
=> true

» client.hooks(repo.full_name).map {|hook| hook[:config][:url]}
=> ["http://currybowl.herokuapp.com/52f2934cec5edd0002000015",
 "https://chefio.atlassian.net/rest/bitbucket/1.0/repository/1118/sync",
 "https://chefio.atlassian.net/rest/bitbucket/1.0/repository/1118/sync",
 "http://localhost:3000/curry/pull_request_updates"]
```

Yep. Added to the hooks is the useless localhost that is the development-environment-computed Rails URL to the callback in Supermarket. Let's resubscribe with something else.

```
» ENV['PUBSUBHUBBUB_CALLBACK_URL'] = 'http://example.com/remove-me'
=> "http://example.com/remove-me"

» subscriber.resubscribe!
   (0.3ms)  BEGIN
  SQL (0.5ms)  UPDATE "curry_repositories" SET "callback_url" = $1, "updated_at" = $2 WHERE "curry_repositories"."id" = 1  [["callback_url", "http://example.com/remove-me"], ["updated_at", "2015-12-02 01:18:54.727622"]]
   (1.2ms)  COMMIT
=> #<Curry::Repository id: 1, owner: "chef", name: "paprika", created_at: "2015-11-25 20:05:27", updated_at: "2015-12-02 01:18:54", callback_url: "http://example.com/remove-me">

» repo.reload
  Curry::Repository Load (0.3ms)  SELECT  "curry_repositories".* FROM "curry_repositories"  WHERE "curry_repositories"."id" = $1 LIMIT 1  [["id", 1]]
=> #<Curry::Repository id: 1, owner: "chef", name: "paprika", created_at: "2015-11-25 20:05:27", updated_at: "2015-12-02 01:18:54", callback_url: "http://example.com/remove-me">

» client.hooks(repo.full_name).map {|hook| hook[:config][:url]}
=> ["http://currybowl.herokuapp.com/52f2934cec5edd0002000015",
 "https://chefio.atlassian.net/rest/bitbucket/1.0/repository/1118/sync",
 "https://chefio.atlassian.net/rest/bitbucket/1.0/repository/1118/sync",
 "http://example.com/remove-me"]
```

Horrah! The webhook to localhost is gone and in it's place, the new equally useless callback_url in my development environment.

**Comment by robbkidd** [comment]
@nellshamrell I think this is review for final review and merge.

**Comment by robbkidd** [comment]
Something to consider as a follow-on to this later is calling `subscriber.resubscribe!` when a curried repository is manually evaluated through the web UI.

**Comment by nellshamrell** [comment]
:shipit:

**Pull request merged**
